data:
  dictionary_type: "separated"
  m_train: 150
  m_test: 80
  P: 3
  J: 6
  sparsity_mode: "max"
  sparsity: 25
  n_search: 3000
  n_sim: 10
  sub_size: 100
  n: 40
  p_edges: 0.162
  p_triangles: 0.7
  seed: 0

algorithm:
  max_sparsity: 26  # 26
  min_sparsity: 25  # 5
  sparsity_freq: 1  # 4
  lambda_: 1e-2
  lambda2: 0.3
  mu: 5
  max_iter: 800
  max_iter_out: 100
  max_iter_tot: 150
  decouple_learning: False
  topo_learning_mode: optimistic
  tol: 1e-7
  tol_out: 1e-3
  patience: 10
  verbose: False
  QP: True
  warmup: 0
  on_test: False
  complete: True
  both: False
  dictionary_types:
    - "classic_fourier"
    - "fourier"
    - "slepians"
    - "wavelet"
    - "edge"
    - "joint"
    - "complete_greedy"
    - "complete_soft"

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      data.J: 2, 4, 6
      # data.p_triangles: 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9 